before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
brews:
  - name: htmltomd
    description: "Convert HTML files to markdown"
    homepage: "https://github.com/david-mk-lawrence/html-to-md"
    tap:
      owner: david-mk-lawrence
      name: homebrew-html-to-md
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
